### PR TITLE
bugfix: Fix distance tolerance in find_attitude

### PR DESCRIPTION
**Pull request by javierggt**
## Description

Distance_tolerance in find_attitude was not being passed because the name was wrong in the template. This fixes this.

## Interface impacts
None

### Unit tests
- [x] No unit tests

Independent check of unit tests by [REVIEWER NAME]
- [ ] [PLATFORM]:

### Functional tests

I tested it in the development server

### CODE REVIEW

**Comment by taldcroft** [comment]
The only thing I would have said, and this can be a future enhancement, is to include the `distance_tolerance` in the solution results page. Also, there is a reference to changing the distance tolerance or mag tolerance, but there is not actually a hook for mag tolerance so that should be removed from the template.

**Comment by javierggt** [comment]
the distance_tolerance is in the results page, because in this PR I also changed the default value in the dialog. True about the mag tolerance.

**Comment by taldcroft** [comment]
> the distance_tolerance is in the results page, because in this PR I also changed the default value in the dialog.

I'm not seeing that. I entered 3.5 and got a solution, but the results page still shows 2.5 as the default.

image

**Comment by javierggt** [comment]
Interesting... it works in the development server.

**Pull request merged**
